#!/usr/bin/env bash
# Install nginx on your web-01
apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTp'
sudo chmod '0777' /var/www/html/index.nginx-debain.html
echo "Hello World!" > /var/www/html/index.nginx-debain.html
sudo /etc/init.d/nginx restart
