#!/usr/bin/env bash
# onfigure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "30i \\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" /etc/nginx/sites-available/default
sudo service nginx restart
