#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html/
sudo chmod -R 0777 /var/www/html/
sudo echo "Hello World!" > /var/www/html/index.html
holder=\
"server {
      listen 80 default_server;
      listen[::]:80 default_server;
      root /var/www/html;
      index index.html index.htm index.neginx-debain.html;
      server_name_;
      location / {
      rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
               try_files $uri $uri/ =401;
	}
}"
sudo chmod -R 0777 /etc/nginx/sites-available/
bash -c "echo '$holder' > /etc/nginx/sites-available/default"
sudo service nginx start
