#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
sudo apt-get update
sudo apt-get install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

file=/etc/haproxy/haproxy.cfg

sudo cp $file $file.copy

sudo sed -i -e '$a\listen appname 3.234.252.139\n\tmode http\n\tstats enable' $file
sudo sed -i -e '$a\\tbalance roundrobin\n\toption httpclose\n\toption forwardfor' $file
sudo sed -i -e '$a\\tserver 17887-web-01 34.236.190.78\n\tserver 17887-web-02 3.237.47.232' $file

sudo service haproxy start
